db:
  image: postgres:9.4
  ports:
    - "5432"

web:
  build: .
  ports:
    - "3000:3000"
  environment:
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD:
    DATABASE_HOST: db
    RAILS_ENV: development
    DOCKERAILS_SECRET: this should be encrypted
    DOCKER_STATE: migrate
  links:
    - db
