default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dockerails_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST'] %>

test:
  <<: *default
  database: dockerails_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>